# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 830dca5ee95e785d9fc3a88ad2873b7de5d67226457d2a91a7fcf3b57a8528e6ec927b7816bbb90e7eaf6ad139e56ede0fcd480d7b2dccb15eda7d6db637bb3d

test:
  secret_key_base: 57933f96a089b40a68e83bb34fc7f0894ade268f81623a3589720e67e413c6919740aff3758b673da47750bbf01d08090be0fa60a24e628e8dc4b7884d6bb48b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
